LIBS

https://www.kaggle.com/datasets/thedevastator/exploring-risk-factors-for-cardiovascular-diseas/data

https://www.kaggle.com/datasets/sulianova/cardiovascular-disease-dataset/data

https://catalog.data.gov/dataset/heart-disease-mortality-data-among-us-adults-35-by-state-territory-and-county-2019-2021

In [1]:
import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

Global Vars

In [2]:
diretorio_atual_projeto = os.getcwd() # Diretório atual do arquivo
notebook_dir_project_predict = os.path.normpath(f"{diretorio_atual_projeto}{os.sep}..{os.sep}..{os.sep}") + os.sep # Diretório do projeto

print(diretorio_atual_projeto)
print(notebook_dir_project_predict)

/home/ed/lgcm/projects/riskPredictionDeseases/dev/notebooks
/home/ed/lgcm/projects/riskPredictionDeseases/

Functions

Scripts

This dataset can be used to explore the risk factors of cardiovascular disease in adults. The aim is to understand how certain demographic factors, health behaviors and biological markers affect the development of heart disease.

To start, look through the columns of data and familiarize yourself with each one. Understand what each field means and how it relates to heart health:

- Age: Age of participant (integer)
- Gender: Gender of participant (male/female).
- Height: Height measured in centimeters (integer)
- Weight: Weight measured in kilograms (integer)
- Ap_hi: Systolic blood pressure reading taken from patient (integer)
- Ap_lo : Diastolic blood pressure reading taken from patient (integer)
- Cholesterol : Total cholesterol level read as mg/dl on a scale 0 - 5+ units( integer). Each unit denoting increase/decrease by 20 mg/dL respectively.
- Gluc : Glucose level read as mmol/l on a scale 0 - 16+ units( integer). Each unit denoting increase Decreaseby 1 mmol/L respectively.             
- Smoke  : Whether person smokes or not(binary; 0= No , 1=Yes).              
- Alco ​­ : Whether person drinks alcohol or not(binary; 0 =No ,1 =Yes ).                     
- Active : whether person physically active or not( Binary ;0 =No,1 = Yes ).    
- Cardio ­­ : whether person suffers from cardiovascular diseases or not(Binary ;0 – no , 1 ­‑yes )

.Identify any trends between the different values for each attribute and the developmetn for cardiovascular disease among individuals represented by this dataset . Age, gender, weight, lifestyle practices like smoking & drinking alcohol are all key influences when analyzing this problem set. You can always modify pieces of your analysis until you're able to find patterns that will enable you make conclusions based on your understanding & exploration. You can further enrich your understanding using couple mopdeling technique like Regressions & Classification models over this dataset alongwith latest Deep Learning approach! Have Fun!

https://www.kaggle.com/datasets/thedevastator/exploring-risk-factors-for-cardiovascular-diseas/data

In [3]:
thousand_70 = pd.read_csv(f'{notebook_dir_project_predict}data{os.sep}input{os.sep}thousand_70{os.sep}heart_data.csv')
thousand_70

,index,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [4]:
thousand_70.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        70000 non-null  int64
 1   id           70000 non-null  int64
 2   age          70000 non-null  int64
 3   gender       70000 non-null  int64
 4   height       70000 non-null  int64
 5   weight       70000 non-null  float64
 6   ap_hi        70000 non-null  int64
 7   ap_lo        70000 non-null  int64
 8   cholesterol  70000 non-null  int64
 9   gluc         70000 non-null  int64
 10  smoke        70000 non-null  int64
 11  alco         70000 non-null  int64
 12  active       70000 non-null  int64
 13  cardio       70000 non-null  int64
dtypes: float64(1), int64(13)
memory usage: 7.5 MB

In [7]:
import numpy as np
import pandas as pd
from ydata_profiling import ProfileReport

df = thousand_70
profile = ProfileReport(df, title="Profiling Report")

In [ ]:
profile